### ISSUE TITLE
PS4 Homebrew games 

### ISSUE THREAD

**Issue by and468860** [red-prig/fpPS4#10]
[ ] PS4 Homebrew games of the fpPS4_30052022 version try to enter the game in the button you can't answer you can do something else I don't know
 game Spelunky Classic HD ja black screen

launch newer emulator by  https://ci.appveyor.com/project/
because the person uses to know uses compiler program thanks.
this uses google translate

 now i5 12500 nvida 3500

![1](https://user-images.githubusercontent.com/61087055/171987621-6d1ff2c7-2505-4c2d-a926-2b2568c484a7.jpg)
![2](https://user-images.githubusercontent.com/61087055/171987628-a69288b0-6ca1-4d17-b84a-38344733f2ad.jpg)
![3](https://user-images.githubusercontent.com/61087055/171987629-02be9189-a95c-48c0-afe4-a1c167daea38.jpg)

**Comment by red-prig** [comment]
@and468860 Please write the full names of the games you have tested so that I can find them, I will test them later. As for appveyor, I don't like it, I'll add a github workflow later.

**Comment by and468860** [comment]
oi https://www.psx-place.com/forums/ps4-homebrew.221/
games 
creeperdiver
Quickz Game v1.0
 Street Racing (GMS's Example 
[Spelunky Classic HD port to PS4

**Comment by red-prig** [comment]
![creeperdiver](https://user-images.githubusercontent.com/68122101/172014032-586a2a18-83b0-463f-ab25-c14f956162e6.png)

I'm not sure if the game should run at 10 fps, but for now at least

**Comment by red-prig** [comment]
Left Stick: WASD
  
  Right Stick: IJKL
  
  Touch pad move: Mouse
  Touch pad click: LMouse
  
  Start: Enter
  
  Pad: Arrows
  
  Triangle: NUM1
  Circle:   NUM2
  Cross:    NUM4
  Square:   NUM5

**Comment by and468860** [comment]
hi thanks some ps4-homebrew games are ok
creeperdiver  
Quickz Game v1.0
Street Racing (GMS's Example

the game Spelunky Classic HD continues screen black screen but game sound runs


have PS4 Homebrew game among others need to fix
Snake Ball v0.3 e doom 64 e BUBBLE BOBBLE 4 FRIENDS The Baron is Back!  

Loading layer library C:\Windows\System32\DriverStore\FileRepository\nvmisi.inf_amd64_2b4d3e6bc3f6629b\.\nvoglv64.dll
Inserted device layer VK_LAYER_NV_optimus (C:\Windows\System32\DriverStore\FileRepository\nvmisi.inf_amd64_2b4d3e6bc3f6629b\.\nvoglv64.dll)
[HostMappedRequirements]
  alignment=256
  memoryType=0,7,8,9,
GPU:000000000B600000..000000001B600000
nop nid:libkernel:0C6306DC9B21AD95:sceKernelSetVirtualRangeName
nop nid:libkernel:EE8C6FDCF3C2BA6A:sceKernelReserveVirtualRange
nop nid:libkernel:0B47FB4C971B7DA7:sceKernelAvailableDirectMemorySize
nop nid:libkernel:A72E8BF2389500DF:sceKernelGetSanitizerMallocReplaceExternal
nop nid:libkernel:B96C96DEFF7CB14E:sceKernelCheckReachability

**Comment by red-prig** [comment]
@and468860 Spelunky Classic is now working by "trunk" branch, check it.

**Comment by red-prig** [comment]
![Spelunky ](https://user-images.githubusercontent.com/68122101/176196677-84d12464-8eee-45ac-82af-80ae42fc9972.png)

**Comment by and468860** [comment]
hello I'm sorry my pc has been burning for days but it now i5 12500 nvida 3500
that the latest fpPS4 update currently such as Spelunky Classic HD and sonic homebrew games on nvidia 3500 does not read.
  Can old graphics card be fixed?

I can't test well with the emulator when I'm going to do it with Lazarus: 2.0.0 gives an error when trying to build ignore error ate da bem .
could you release the latest version of the emulator for you to dowld on the site so that people don't know how to do Building

I'm using google translate


![sonic](https://user-images.githubusercontent.com/61087055/176375973-5d639a48-5895-435d-a342-d8bbf603f59c.png)
sonic mania
![Spelunky Classic HD](https://user-images.githubusercontent.com/61087055/176376183-16b9c1d0-fb4f-4f63-a875-da0e2979da52.png)
Spelunky Classic HD
![Street Racing](https://user-images.githubusercontent.com/61087055/176376206-994aafbc-f611-4b01-a74b-8e67536e8997.png)
Street Racing]

**Comment by red-prig** [comment]
@and468860 try it build https://github.com/red-prig/fpPS4/releases/tag/draft29062022

**Comment by and468860** [comment]
thank you all right now

**Comment by and468860** [comment]
could deployment of the graphic run more game

MegaManLegacyCollection
ACA NEOGEO SPIN MASTER
Cladun Returns This is Sengoku!
VSurfaceFormat:VK_FORMAT_B8G8R8A8_SRGB

Adventures of Pip
Frozen free fall
sceMouseInit

CircuitBreakers
sceSysmoduleLoadModule:SCE_SYSMODULE_NP_TROPHY
g_trophyids[0] = 0
id_list.userId[0] = 1
g_trophyContext[0] = -1
sceNpTrophyCreateContext
sceNpTrophyCreateHandle
sceNpTrophyRegisterContext:3333
sceNpTrophyDestroyHandle:3333
after g_trophyids[0] = 1

**Comment by thx4ever** [comment]
Practically all games base on Yoyo running engine work with this emulator

**Comment by red-prig** [comment]
There are still problems on some games of this engine, I still can't run Momodora normally.

**Comment by and468860** [comment]
new game Run
An Untitled Story
A.Bastards.Tale     20fs 
Bards.Gold.            20fs
Undertale

**Comment by and468860** [comment]
Try fix game  screen black
Minit.PS4-CUSA09747
Cladun Returns This is Sengoku!

**Comment by red-prig** [comment]
everything has its time

**Comment by and468860** [comment]
work fix it 

sceKernelVirtualQuery sceKernelSetVirtualRangeName

 currently the emulator is now sceKernelSetVirtualRangeName after correct games algon game ff9 e another game
now emulator read game because to read must impacao syten or module


well already correct sceKernelSetVirtualRangeName he just fix something other games

to fix this use module as the original ps4 console he file sprx and change to prx that emulator reads

if you use the module everything will have more to fix
that there are now a lot of them nid :libkernel:9E1D8814C80A4EFF:kqueue and nop nid:libSceNpCommon:B84C1A83FD1864F7:sceNpMutexInit other I don't know

well I have module version 3,5,8.5 already lost algon

**Comment by red-prig** [comment]
@and468860 I do not understand the meaning of such a strange and short English

**Comment by red-prig** [comment]
@and468860
wat you mean with "syten"?
ff9 is final fantasy?
in which game did you meet 9E1D8814C80A4EFF:kqueue and B84C1A83FD1864F7:sceNpMutexInit ?

**Comment by and468860** [comment]
I mean the system I want to say the last update was good yesterday because I fixed it sceKernelSetVirtualRangeName Some game starts because the reading emulator stops reading Many games like Final Fantasy 9 etc.


To fix this and another modulo
do not deploy from the emulator.

don't leave to read use prx ps4 module files
 to sce module emulator prx files folder,
 he asks to fix it
9E1D8814C80A4EFF:kqueue and nop nid:libSceNpCommon:B84C1A83FD1864F7:sceNpMutexInit

**Comment by red-prig** [comment]
@and468860 please explain what you mean by "don't leave to read emulador use prx ps4 module files"

**Comment by and468860** [comment]
bad translation from google play that says emulator like this now.
when a game
start by the emulator last seconds to read the game closed emuldor some games to fix this use prx files folder sce module to continue reading by the emulator do
video you see I want to say

**Comment by red-prig** [comment]
I understand that you are talking about the files loaded by the emulator, but the final context is not at all clear to me. Yes, at the moment, to run some games, in particular, dump files from the console are required: libSceNgs2.prx libScePngDec.prx libSceRtc.prx

**Comment by and468860** [comment]
i have some prx not all version 3 ; 5 , 8.5 want to download my

**Comment by red-prig** [comment]
Do you offer your dumped files or ask me for them? Your automatic translator is terrible.

**Comment by red-prig** [comment]
@and468860 Do you have Discord? you can send me a link to the files in PM. (red_prig#9505)

**Comment by and468860** [comment]
Yes Google files

**Comment by and468860** [comment]
Files my modulo

**Comment by red-prig** [comment]
@and468860 I sent a welcome mail to your email

**Comment by and468860** [comment]
tarecamiao123@gmail.com

**Comment by red-prig** [comment]
omg you chose a strange way, you could just send a link to the file in google drive in an email

**Comment by red-prig** [comment]
I tested Desert.Child with the same problem as this ticket:  https://github.com/red-prig/fpPS4/issues/18
someday I'll get my hands on it

**Comment by and468860** [comment]
black  screen Cladun Returns This is Sengoku!
imagens  new    Gem.Smashers 
![Gravar_2022_07_20_06_12_47_762 mp4_snapshot_00 26 303](https://user-images.githubusercontent.com/61087055/179902505-f4b332cf-08ac-4d94-83ff-f092543723e0.jpg)

**Comment by red-prig** [comment]
I've been testing these games while I'm rewriting different components

**Comment by danni551** [comment]
I recommend using deepl.com as a translator :]

**Comment by and468860** [comment]
good job my god it can be fix UnityEngine the game already read
have something
  many problems game wants this fix Return of the Obra Dinn etc.
libScePad:01CB25A4DD631D1F:scePadDeviceClassGetExtendedInfor

  and game Homebrew games  https://pkg-zone.com/
Duck Hunt Remake 1.01 PS4 - Lapy
bustyandbuster DX etc.

**Comment by red-prig** [comment]
@and468860 What game is this and what video card do you have? Also try adding the emulator launch option:
`-h MEMORY_BOUND_HACK`

**Comment by and468860** [comment]
my pc nvidia 3050 4 bg  intel 12500 i5 
want new module files update and new file module [tarecamiao123@gmail.com](mailto:tarecamiao123@gmail.com)
this only gives games that use UnityEngine
vkAllocateMemory:VK_ERROR_OUT_OF_DEVICE_MEMORY
BeginThread:BackgroundWorker:0000000008D4D210
An unhandled exception occurred at $0000000100083031:
EAssertionFailed: Assertion failed (vMemory.pas, line 685)

**Comment by red-prig** [comment]
@and468860 This is strange, try not to put it in the sce_module folder next to the emulator, nothing but the files: libSceNgs2.prx and libScePngDec.prx maybe some module initialization gives this error.

**Comment by red-prig** [comment]
@and468860 What versions of modules do you have? 9.0 and above is relevant for me.

**Comment by dagas3** [comment]
send me all the .prx files by email, please, thanks.
dagas3@hotmail.com

**Comment by red-prig** [comment]
@dagas3 https://discord.gg/up9qatpX7M -> #files

**Comment by ghost** [comment]
> ![creeperdiver](https://user-images.githubusercontent.com/68122101/172014032-586a2a18-83b0-463f-ab25-c14f956162e6.png)
> 
> I'm not sure if the game should run at 10 fps, but for now at least

It's supposed to run at 30 FPS
