### ISSUE TITLE
Error message even when everything is in its correct folder

### ISSUE THREAD

**Issue by TDOGH** [red-prig/fpPS4#106]
So far everything is working but when I launch a game I get "nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue ", and nothing loads. How do I fix this?. Note I'm trying to run Bloodborne GotY edition, and am unsure if this game is unavailable with this emulator yet
![image_2023-03-21_081813402](https://user-images.githubusercontent.com/128463464/226550553-eba7eb9f-caeb-466f-bd0c-621ee33822aa.png)

**Comment by ghost** [comment]
Bloodborne is not supported on this emulator, look in the compatibility list and try something else.

**Comment by red-prig** [comment]
At the moment, part of the functionality has not yet been developed, therefore it does not start
