### ISSUE TITLE
Wierd Graphic Glitches in Sonic Mania

### ISSUE THREAD

**Issue by Arceus55** [red-prig/fpPS4#108]
I have these glitches and i don't know what to do?:
![Screenshot 2023-03-25 163518](https://user-images.githubusercontent.com/128918565/227727260-dcbf07bd-72fd-4a10-bb0e-159a5131cf7e.jpg)

Here my Log:
[Log_Sonic_Mania_Sat_Mar_25_2023_16_41_11.log](https://github.com/red-prig/fpPS4/files/11069303/Log_Sonic_Mania_Sat_Mar_25_2023_16_41_11.log)

**Comment by red-prig** [comment]
Use the setting to solve the problem: -h DISABLE_SRGB_HACK
As long as it is.
