### ISSUE TITLE
Subnautica won't start?

### ISSUE THREAD

**Issue by Arceus55** [red-prig/fpPS4#109]
is it just me or why won't Subnautica start?

[Log_Subnautica_Below_Zero_Sat_Mar_25_2023_17_1_10.log](https://github.com/red-prig/fpPS4/files/11069354/Log_Subnautica_Below_Zero_Sat_Mar_25_2023_17_1_10.log)

[Log_Subnautica_Below_Zero_Sat_Mar_25_2023_17_7_3.log](https://github.com/red-prig/fpPS4/files/11069357/Log_Subnautica_Below_Zero_Sat_Mar_25_2023_17_7_3.log)

I know there is a list of compatible games but i am not able to open it..

**Comment by ghost** [comment]
Subnautica is not supported on fpPS4, find something else in the compatibility list that's at least "boots" to "playable".

**Comment by Arceus55** [comment]
ok thx
