### ISSUE TITLE
fpPS4 gets an access violation if minimized

### ISSUE THREAD

**Issue by ghost** [red-prig/fpPS4#112]
Every single time I minimize, fpPS4 crashes with an access violation. I attached a video to show proof:

https://user-images.githubusercontent.com/86171223/230215795-64c479c2-5f1a-431c-92e0-ce24bc6d3b26.mp4

I hope this gets fixed. (Yes, in the video I clicked Minimize in fpPS4)

**Comment by red-prig** [comment]
@ArbestRi  I can't reproduce this crash in any way, try the version with debug symbols, maybe it will give more information
[fpPS4_3dfcab8_debug.zip](https://github.com/red-prig/fpPS4/files/11177561/fpPS4_3dfcab8_debug.zip)

**Comment by billyboybob** [comment]
https://user-images.githubusercontent.com/61484364/230727167-dc203131-961c-498b-9c61-af5068cb0fb6.mp4

tested with debug symbols build posted here (i know im not ArbestRi, but still)

error:
```
An unhandled exception occurred at $00007FFE5FEB02C3:
EAccessViolation: Access violation
  $00007FFE5FEB02C3
  $0000000100130582  DESTROY,  line 507 of vulkan/vImage.pas
  $000000010000FE5B
  $000000010003E407
  $000000010009B956  RECREATESWAPCHAIN,  line 565 of vulkan/vFlip.pas
  $000000010009BD0C  FLIP,  line 658 of vulkan/vFlip.pas
  $000000010006CC92  SCEVIDEOOUTSUBMITFLIP,  line 1394 of src/ps4_libscevideoout.pas
  $000000010006A6A9  ONIDLEUPDATE,  line 321 of src/ps4_libscevideoout.pas
  $000000010017DAB1  NOTIFYIDLEHANDLER,  line 712 of include/application.inc
  $000000010017D3B0  IDLE,  line 443 of include/application.inc
  $000000010017F0F8  HANDLEMESSAGE,  line 1265 of include/application.inc
  $000000010017F5D1  RUNLOOP,  line 1405 of include/application.inc
  $00000001001A0695  APPRUN,  line 54 of include/interfacebase.inc
  $000000010017F56B  RUN,  line 1388 of include/application.inc
  $000000010006A828  APP_RUN,  line 354 of src/ps4_libscevideoout.pas
  $0000000100004771  main,  line 477 of fpPS4.lpr
  $0000000100005056
```

**Comment by red-prig** [comment]
@billyboybob @ArbestRi Test again if the problem is gone 
[fpPS4_debug.zip](https://github.com/red-prig/fpPS4/files/11183682/fpPS4_debug.zip)

**Comment by billyboybob** [comment]
https://user-images.githubusercontent.com/61484364/230745051-d5f06d4d-2910-41bf-a1ad-16ef6b258704.mp4

retested with binary sent here
no crash when minimizing the fpPS4 window :)
