### ISSUE TITLE
fpPS4 problem

### ISSUE THREAD

**Issue by AbdoHassan2023** [red-prig/fpPS4#113]
I ran the emulator..but this screen appears to me..can you help me..what am I missing..or where is the problem?
![Capture](https://user-images.githubusercontent.com/130133074/230559409-ee5bbdfc-dc6d-449c-80e2-8bd246b15b74.JPG)

**Comment by gandalfthewhite19890404** [comment]
What is you PC specs?

**Comment by red-prig** [comment]
Your video driver does not support vulkan api, which means that you either did not install the video driver at all, or your computer does not meet the minimum system requirements
