### ISSUE TITLE
fpPS4 problem

### ISSUE THREAD

**Issue by AbdoHassan2023** [red-prig/fpPS4#116]
I ran the emulator..but this screen appears to me..can you help me..what am I missing..or where is the problem?
![Capture](https://user-images.githubusercontent.com/130133074/230749453-9b762c0d-5103-4f2f-a55d-7f13d331af47.JPG)

**Comment by ghost** [comment]
CTR Nitro Fueled isn't supported on fpPS4. Try something else in the compatibility list, don't do the ones that are "nothing" status.

**Comment by AbdoHassan2023** [comment]
> CTR Nitro Fueled isn't supported on fpPS4. Try something else in the compatibility list, don't do the ones that are "nothing" status.


Is there a list of supported games?

**Comment by AbdoHassan2023** [comment]
Is there a list of supported games?

**Comment by gandalfthewhite19890404** [comment]
https://github.com/red-prig/fpps4-game-compatibility/issues

**Comment by gandalfthewhite19890404** [comment]
CLose it
