### ISSUE TITLE
nop nid:libScePosix:6B63FDC1819E66F7:pthread_setprio error

### ISSUE THREAD

**Issue by Traspert** [red-prig/fpPS4#117]
Pls help me! I dont know what this is.
![image](https://user-images.githubusercontent.com/130299951/230780638-80917f78-f2b9-4b23-872f-3260959762fc.png)

**Comment by ghost** [comment]
Ratchet & Clank is not supported on fpPS4, try something else like Sonic Mania or Oceanhorn.
