### ISSUE TITLE
game  ERROR nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue

### ISSUE THREAD

**Issue by adamaymanalbeetar** [red-prig/fpPS4#119]
when i launch P.T. I get this error nop 

nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue

![image](https://user-images.githubusercontent.com/99988232/232070840-83cec828-9f4a-4eea-b4bb-f4e2f1e1b57f.png)

and also this 
![image](https://user-images.githubusercontent.com/99988232/232070981-58fb89ab-eeeb-4989-94e1-75cbc6e859b6.png)

and this 

![image](https://user-images.githubusercontent.com/99988232/232071097-25e3efde-d5dc-499b-9b02-453542232f0c.png)

and this 

![image](https://user-images.githubusercontent.com/99988232/232071177-534d5fe3-5fed-4e2d-a2d2-991ea5c7856e.png)

**Comment by red-prig** [comment]
@adamaymanalbeetar PT is not supported yet, please see the compatibility list https://github.com/red-prig/fpps4-game-compatibility/issues/430

**Comment by adamaymanalbeetar** [comment]
> @adamaymanalbeetar PT is not supported yet, please see the compatibility list [red-prig/fpps4-game-compatibility#430](https://github.com/red-prig/fpps4-game-compatibility/issues/430)

sorry for interrupting thxs for telling me :)
