### ISSUE TITLE
CUSA03173

### ISSUE THREAD

**Issue by Simpbizkit** [red-prig/fpPS4#120]
When I try to load Bloodborne I am met with these errors 
<img width="282" alt="Bloodborne error 2" src="https://user-images.githubusercontent.com/131321795/233241240-08665496-b95a-47ba-99a4-0e3ea95c867c.PNG">
<img width="367" alt="Bloodborne error" src="https://user-images.githubusercontent.com/131321795/233241286-d66b1130-cb69-4b48-9765-3304ac8f8df3.PNG">
Anyone got some insight on this? Last time I checked Bloodborne was on the compatibility list

**Comment by red-prig** [comment]
The fact that it is in the compatibility list means that it has been tested nothing more, carefully look at the status of the game
