### ISSUE TITLE
Game Not Loading

### ISSUE THREAD

**Issue by KT7000** [red-prig/fpPS4#123]
The pkgeditor software keeps crashing whenever I export a pkg fle to the Games folder. The pkg file is 30GB and I have around 150GB is hard drive space.

**Comment by KT7000** [comment]
Ok, seems the problem was it takes a while for the pkg to export. About 15-20 minutes.

When I hit Run fpPS4, it loads like it's supposed to, but the game doesn't show. It's kust a blank screen in the window.

**Comment by ghost** [comment]
@red-prig Close this issue, @KT7000 is running an unsupported game

**Comment by ArdaUzun-55** [comment]
Like the other commentor mentioned, you are probably playing a game which does not currently work in the emulator. You can look in the compatibility list to see what the current progress in the game is. (E.g. go search "GAMENAME" in https://github.com/red-prig/fpps4-game-compatibility/issues and then you will find a category named status-XXXX near the title)
XXXX = nothing, menus, ingame, playable.

**Comment by gandalfthewhite19890404** [comment]
How much RAM you have?
Big PKGs requires HUGE of RAM, there is a memory usage/leak issue in PKGEditor.

**Comment by ArtemVideoGames** [comment]
> How much RAM you have? Big PKGs requires HUGE of RAM, there is a memory usage/leak issue in PKGEditor.

His issue with PKG Editor resolved, now issue maybe in running incompatible game

**Comment by KT7000** [comment]
It's Final Fantasy X/X-2 HD Remaster.

**Comment by KimieStar** [comment]
@KT7000 Don't discuss this any further!!! If you have problems either join the discord or use the compatibility repo!!!

**Comment by gandalfthewhite19890404** [comment]
Close it as solved, pls

**Comment by red-prig** [comment]
This game is not supported yet https://github.com/red-prig/fpps4-game-compatibility/issues/213
