### ISSUE TITLE
The Limbo Game attempts to start with black screen but then crashes with following errors.

### ISSUE THREAD

**Issue by red-prig** [red-prig/fpPS4#13]
The Limbo Game attempts to start with black screen but then crashes with following errors.

>sceKernelSetEventFlag:00000000084638E0:ManualResetEvent_c:0000000000000001:15764
ParamGetInt:1
sceSysmoduleLoadModule:00A8
sceSysmoduleLoadModule:00AC
sceSysmoduleLoadModule:00A4
sceSysmoduleLoadModule:00A0
sceCommonDialogInitialize
sceErrorDialogInitialize
nop nid:libSceNpCommerce:D1A4766969906A5E:sceNpCommerceDialogInitialize
Message: No error. (0)
  $00007FFDE77DD532
  $00000000001B0350 fpPS4.exe

_Originally posted by @AussiePlick in https://github.com/red-prig/fpPS4/issues/1#issuecomment-1151007449_

**Comment by gandalfthewhite19890404** [comment]
Suggest to close, as game-related issue was created in game-compatibility repository.
