### ISSUE TITLE
how to build fpPS4?

### ISSUE THREAD

**Issue by Aextoxicon** [red-prig/fpPS4#133]
![屏幕截图(58)](https://github.com/red-prig/fpPS4/assets/100518201/9df4e72a-a0c1-479e-8061-49ae2e99279f)
I finished the build and...It can't run
我编译完源代码以后发现exe没法运行，提示我缺少了一些dll，不能运行。。。
以及在这之前lazrous在编译过程中报出了许多错误（虽然并没有因此停止编译）
关于报错如果有日志的话应该会保存在里面，但是我不清楚日志在哪里。
有一点很抱歉因为这个输入法（也是电脑上目前唯一的输入法）输入英文非常的蹩脚，实在没办法才用的中文😞😞😞

**Comment by red-prig** [comment]
Apparently your build completes successfully, but why the application does not start is another question, you did not show any errors, if you did not understand how to start the application, you can press F9. Also, you didn't mention which version you are trying to compile and whether your processor supports AVX2 instructions.
