### ISSUE TITLE
Can't launch UFC 4

### ISSUE THREAD

**Issue by generator22** [red-prig/fpPS4#135]
DT_SCE_IMPORT_LIB_ATTR  :000A:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :001F:libSceAppContent
DT_SCE_IMPORT_LIB_ATTR  :001F:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0020:libSceAppContentPft
DT_SCE_IMPORT_LIB_ATTR  :0020:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :001C:libSceAudio3d
DT_SCE_IMPORT_LIB_ATTR  :001C:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :000B:libSceAudioIn
DT_SCE_IMPORT_LIB_ATTR  :000B:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :001B:libSceAudioOut
DT_SCE_IMPORT_LIB_ATTR  :001B:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0021:libSceCommonDialog
DT_SCE_IMPORT_LIB_ATTR  :0021:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0023:libSceGameLiveStreaming
DT_SCE_IMPORT_LIB_ATTR  :0023:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :001E:libSceGnmDriver
DT_SCE_IMPORT_LIB_ATTR  :001E:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0024:libSceHttp
DT_SCE_IMPORT_LIB_ATTR  :0024:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0019:libSceIme
DT_SCE_IMPORT_LIB_ATTR  :0019:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0025:libSceImeDialog
DT_SCE_IMPORT_LIB_ATTR  :0025:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0026:libSceInvitationDialog
DT_SCE_IMPORT_LIB_ATTR  :0026:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0027:libSceJson2
DT_SCE_IMPORT_LIB_ATTR  :0027:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0028:libSceMsgDialog
DT_SCE_IMPORT_LIB_ATTR  :0028:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0029:libSceNet
DT_SCE_IMPORT_LIB_ATTR  :0029:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :002A:libSceNetCtl
DT_SCE_IMPORT_LIB_ATTR  :002A:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :002B:libSceNpAuth
DT_SCE_IMPORT_LIB_ATTR  :002B:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :002C:libSceNpCommerce
DT_SCE_IMPORT_LIB_ATTR  :002C:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :002D:libSceNpCommon
DT_SCE_IMPORT_LIB_ATTR  :002D:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :002E:libSceNpManager
DT_SCE_IMPORT_LIB_ATTR  :002E:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :002F:libSceNpProfileDialog
DT_SCE_IMPORT_LIB_ATTR  :002F:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0030:libSceNpTrophy
DT_SCE_IMPORT_LIB_ATTR  :0030:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0031:libSceNpWebApi
DT_SCE_IMPORT_LIB_ATTR  :0031:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0032:libScePad
DT_SCE_IMPORT_LIB_ATTR  :0032:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0033:libScePlayGo
DT_SCE_IMPORT_LIB_ATTR  :0033:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0015:libSceRandom
DT_SCE_IMPORT_LIB_ATTR  :0015:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0035:libSceRemoteplay
DT_SCE_IMPORT_LIB_ATTR  :0035:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0036:libSceRtc
DT_SCE_IMPORT_LIB_ATTR  :0036:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0037:libSceSaveData
DT_SCE_IMPORT_LIB_ATTR  :0037:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0038:libSceSaveDataDialog
DT_SCE_IMPORT_LIB_ATTR  :0038:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0039:libSceScreenShot
DT_SCE_IMPORT_LIB_ATTR  :0039:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :003A:libSceSharePlay
DT_SCE_IMPORT_LIB_ATTR  :003A:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :003B:libSceSsl
DT_SCE_IMPORT_LIB_ATTR  :003B:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :003C:libSceSysmodule
DT_SCE_IMPORT_LIB_ATTR  :003C:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :003D:libSceSystemService
DT_SCE_IMPORT_LIB_ATTR  :003D:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :001A:libSceUsbd
DT_SCE_IMPORT_LIB_ATTR  :001A:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :003E:libSceUserService
DT_SCE_IMPORT_LIB_ATTR  :003E:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :003F:libSceVideoOut
DT_SCE_IMPORT_LIB_ATTR  :003F:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0040:libSceVideoRecording
DT_SCE_IMPORT_LIB_ATTR  :0040:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0041:libSceVoice
DT_SCE_IMPORT_LIB_ATTR  :0041:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :001D:libSceWebBrowserDialog
DT_SCE_IMPORT_LIB_ATTR  :001D:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0043:libc
DT_SCE_IMPORT_LIB_ATTR  :0043:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0022:libSceCoredump
DT_SCE_IMPORT_LIB_ATTR  :0022:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0034:libScePosix
DT_SCE_IMPORT_LIB_ATTR  :0034:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0042:libkernel
DT_SCE_IMPORT_LIB_ATTR  :0042:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_IMPORT_LIB       :0000:libkernel_module_info
DT_SCE_IMPORT_LIB_ATTR  :0000:0:0:AUTO_EXPORT|LOOSE_IMPORT
DT_SCE_FILENAME:C:/p4/UFC/RL4_24.00/build/runtime/ufckettlezf.elf:0000
DT_SCE_MODULE_INFO:ufckettlezf:0000
DT_SCE_MODULE_ATTR      :0000:0:0:NONE
.CODE:0000000800000000..00000008024F9000  0000000000004000..00000000024FD000
.RELR:0000000802600000..00000008027DF000  0000000002500000..00000000026DF000
.DATA:0000000802800000..0000000802DDB000  00000000026E0000..0000000002CBB000
.RDOL:0000000802800000..0000000802800098
.RDOL:000000080243FA58..00000008024F810C
patch_tls_count=55
Warn, file libc.prx not loaded!
Warn, file libSceVideoRecording.prx not loaded!
Warn, file libSceSharePlay.prx not loaded!
Warn, file libSceJson2.prx not loaded!
Warn, file libSceGameLiveStreaming.prx not loaded!
Warn, file libSceWebBrowserDialog.prx not loaded!
Warn, file libSceAudio3d.prx not loaded!
Warn, file libSceUsbd.prx not loaded!
Warn, file libSceSsl2.prx not loaded!
Warn, file libSceNpAuth.prx not loaded!
Warn, file libSceInvitationDialog.prx not loaded!
Warn, file EAWebKit.prx not loaded!
Warn^:libc:Need_sceLibc:3F7DF43F774517AF
Warn^:libc:_Stdin:D530E8FC89AA9097
Warn^:libc:_Stdout:DAC5B3858A851F81
Warn^:libc:_Stderr:1FC029ACA799B4D8
MAPF:0000000800000000..0000000802DDC000
PF_X:0000000800000000..00000008024F9000:TRUE
STUB:00000008024F810C..00000008024F9000
pthread_attr_init
pthread_create:0000000100070EE0 main
pthread_attr_destroy
BeginThread:main:0000000100070EE0
mapCodeInit:eboot.bin
Entry:00000000000016C0
nop nid:libc:6F3404C72D7CF592:_init_env

**Comment by red-prig** [comment]
Nobody said that the emulator supports UFC 4
