### ISSUE TITLE
unable to play using keyboard

### ISSUE THREAD

**Issue by parik309** [red-prig/fpPS4#138]
I have got everything correct and game is loading just fine. Only issue is that keyboard is not working. Even after pressing 'ESC' key on keyboard, configuration window appears but I am unable to change the configuration.
I tried to manually create config file and the load preset in emulator still it doesn't help and I am not able to get it working.

**Comment by Addy2004** [comment]
make a bat file where you have put `fpps4.exe`
and write this following command in it

`
start fpps4.exe -e "<path of your game (to eboot.bin)>" -pad "keyboard"
`
we will update the pad customization options on the homepage soon

**Comment by parik309** [comment]
thanks for the response, I attached a gamepad and its working fine so didn't try the solution that you gave, however you didn't mention the bat filename. I dont think this would work with any random name.

**Comment by Addy2004** [comment]
Any file name would work, the emulator is configured to accept xinput (xbox controllers) by default. That's why attaching a gamepad made it receive inputs. But to send inputs via keyboard, you will have to switch the pad state using the above command.
