### ISSUE TITLE
Access Violation(Invalid Memory Read?!) (Hue)

### ISSUE THREAD

**Issue by JustAHippo** [red-prig/fpPS4#14]
[HostMappedRequirements]
  alignment=256
  memoryType=0,1,2,3,
GPU:0000000080000000..0000000100000000
KernelGetProcParam
call_dt_preinit_array:0
mapCodeInit:eboot.elf
EntryPoint:00000000000000A0
Message: Access violation (216)
  $00000000089E9C8C offset $00059C8C libc.prx:_ZNSt8ios_base5clearENSt5_IosbIiE8_IostateEb+$00000A6C
  $00000000089E8BDB offset $00058BDB libc.prx:_ZNSt8ios_base4InitC1Ev+$0000024B
  $0000000007249643 offset $00039643 eboot.elf:EntryPoint+$000395A3
  $00000000072100D2 offset $000000D2 eboot.elf:EntryPoint+$00000032
  $000000010005603F fpPS4.exe
[TWin32WidgetSet.Destroy] WARNING: There are 1 TimerInfo structures left, I'll free them
Message: Access violation (216)
  $0000000000F58021

This is likely caused by reading the game instructions incorrectly. It occurs on the game **Hue**

**Comment by red-prig** [comment]
I fixed some of the errors, but at the moment it displays a black screen, it is not yet clear why.

**Comment by red-prig** [comment]
![hue](https://user-images.githubusercontent.com/68122101/196451964-11b26285-c50e-48f0-9841-465b27c75d6a.png)
main menu show with now!
