### ISSUE TITLE
Bloodborne CUSA03173

### ISSUE THREAD

**Issue by Rkaksdksrud** [red-prig/fpPS4#141]
I get this error
nop nid:libSceGnmDriver:DBDA0ABCA5F3119A:sceGnmMapComputeQueue

and also this

Warn, file libSceAvPlayer.prx not loaded!
Warn, file libSceVideoRecording.prx not loaded!
Warn, file libSceGameLiveStreaming.prx not loaded!
Warn, file libSceWebBrowserDialog.prx not loaded!
Warn, file libSceNpAuth.prx not loaded!
Warn, file libSceNpUtility.prx not loaded!
Warn, file libSceSsl.prx not loaded!
Redirected:DAC5B3858A851F81:_Stdout
Redirected:3148C2E256C7ACAE:fflush
Redirected:9FB01EA70474B37E:mktime
Redirected:C0B9459301BD51C4:time
Redirected:79F84AFD84946184:localtime
Redirected:D6679C3FB4602360:gmtime
Redirected:E5B05A7062F22CEB:gmtime_s

**Comment by red-prig** [comment]
Bloodborne  is still not supported

**Comment by MrJerold** [comment]
how could i get this pkg

**Comment by red-prig** [comment]
> how could i get this pkg

This is exclusively your problem, we cannot help you with this.

**Comment by MrJerold** [comment]
I've just searched all around. None pkgs anywhere on any website

**Comment by red-prig** [comment]
> I've just searched all around. None pkgs anywhere on any website

No one will provide you with links, it's not legal, please stop asking.

**Comment by MrJerold** [comment]
Still. Hand them pkgs
