### ISSUE TITLE
Game cannot play

### ISSUE THREAD

**Issue by Stwarberry** [red-prig/fpPS4#146]
![Desktop Screenshot 2023 12 03 - 14 38 00 04](https://github.com/red-prig/fpPS4/assets/152767515/03296c94-18ce-4359-b4ff-2535ac6d26e7)
Log say: ERROR - (Updater) Unable to locate selected CI workflow from fpPS4 GitHub! How to fix? 
Game failed to run (Nickelodeon All Star Brawl 2)

**Comment by elonthelad** [comment]
1) You have not installed fpps4 correctly
2) this game does not run yet
3) do not make issues on the main github for game compatibility

**Comment by Stwarberry** [comment]
> 1. You have not installed fpps4 correctly
> 2. this game does not run yet
> 3. do not make issues on the main github for game compatibility

Check if I wrong or missing. I just follow tutorial on youtube. 
![Desktop Screenshot 2023 12 03 - 19 38 38 30](https://github.com/red-prig/fpPS4/assets/152767515/e7510350-e98e-4c07-aabf-1d4dfe53f620)
![Desktop Screenshot 2023 12 03 - 19 39 33 31](https://github.com/red-prig/fpPS4/assets/152767515/3dfae900-2464-4086-959f-ea482c04f9a5)
![Desktop Screenshot 2023 12 03 - 19 39 44 39](https://github.com/red-prig/fpPS4/assets/152767515/4bbde00a-7712-40ff-9302-6636e578d019)

**Comment by elonthelad** [comment]
youtube tutorials are outdated. use this https://github.com/KimieStar/Pkg-Editor-2023

**Comment by Stwarberry** [comment]
> youtube tutorials are outdated. use this https://github.com/KimieStar/Pkg-Editor-2023

ok, is my Emu and lib folder correct?? but why FpPS4 error log? it is latest version

**Comment by Stwarberry** [comment]
![Desktop Screenshot 2023 12 03 - 20 33 59 21](https://github.com/red-prig/fpPS4/assets/152767515/b1832b8e-74eb-4b0e-a45f-c8215e940eb9)
 it say: 
 To update fpPS4, you will need to open settings and select "Main CI" in "Current workflow", located on fpPS4 updater section. After selecting, click on "Apply and Close", close launcher window and open it again.
 
 I dont know how to do

**Comment by elonthelad** [comment]
join the discord if you want actual help. this repo is not for general support

**Comment by Stwarberry** [comment]
> join the discord if you want actual help. this repo is not for general support

ok do u have discord link?

**Comment by elonthelad** [comment]
try looking on the repo readme

**Comment by red-prig** [comment]
https://discord.gg/up9qatpX7M

**Comment by Stwarberry** [comment]
Thanks you
