### ISSUE TITLE
huh

### ISSUE THREAD

**Issue by SpareEnderboy** [red-prig/fpPS4#147]
**so for some reason intel core i5 10500f crashes opening fpps4**

**Comment by red-prig** [comment]
There is too little information to understand anything.

**Comment by SpareEnderboy** [comment]
**CPU** - Intel Core 15 10500f
**GPU** - Intel UHD Graphics 630 (iGPU)
**RAM** - 16GB
**OS** - Windows 11 Professional x64
**ERROR** - fpPS4 immediately crashes upon opening. I am not running it as administrator btw.
**NOTES** \\/
- My PC also emulates PS1, emulates PS2, and barely emulates PS3 (vulkan crashes galore in RPCS3)

**Comment by red-prig** [comment]
This is not what I wanted from you, most likely your processor does not support the avx2 extension or you configured the emulator incorrectly, and the characteristics of your PC do not give me any information.

**Comment by SpareEnderboy** [comment]
> This is not what I wanted from you, most likely your processor does not support the avx2 extension or you configured the emulator incorrectly, and the characteristics of your PC do not give me any information.

thx now i need ryzen 9 5900x

**Comment by SpareEnderboy** [comment]
> Programs using Advanced Vector Extensions (AVX) will run on this processor, boosting performance for calculation-heavy applications. Besides AVX, Intel is including the newer AVX2 standard, too, but not AVX-512.

THAT WOULDVE BEEN GOOD TO KNOW

**Comment by SpareEnderboy** [comment]
On the website I have open with my CPU specs, it supports:

- MMX
- SSE
- SSE2
- SSE3
- SSSE3
- SSE4.2
- AVX
- AVX2
- EIST
- Intel 64
- XD bit
- VT-x
- VT-d
- AES-NI
- TSX
- TXT
- CLMUL
- FMA3
- F16C
- BMI1
- BMI2
- ABM
- ADX
- RdRand
- TBT 2.0

**Comment by SpareEnderboy** [comment]
> "Put` libSceNgs2.prx and etc. here" 

lol ok
wheres libSceNgs2,prx

**Comment by red-prig** [comment]
The problem may be the most trivial, due to the fact that the emulator does not have a graphical interface (you have not provided any specifics about the error), secondly, go to our discord and read the installation tutorial

**Comment by gandalfthewhite19890404** [comment]
@SpareEnderboy Run fpps4 from command line and post output here.
