### ISSUE TITLE
Cursed Castila EX exception

### ISSUE THREAD

**Issue by thx4ever** [red-prig/fpPS4#15]
Hi, the game Cursed Castila EX boot but when i press the key to start the game it trow this exception

An unhandled exception occurred at $0000000100220919:
EAssertionFailed: VOP3a?423 (emit_vop3.pas, line 989)
  $0000000100220919  _EMIT_SPI,  line 1722 of spirv/SprvEmit.pas
  $000000010021CE2C  NEXTPARSE,  line 262 of spirv/SprvEmit.pas
  $000000010021CC69  PARSE,  line 222 of spirv/SprvEmit.pas
  $00000001000AB84C  PARSESHADER,  line 208 of vulkan/vShaderManager.pas
  $00000001000ABC05  _FETCHSHADER,  line 318 of vulkan/vShaderManager.pas
  $00000001000ABDD8  FETCHSHADER,  line 355 of vulkan/vShaderManager.pas
  $000000010006AAF1  UPDATEGPUREGSINFO,  line 1727 of chip/ps4_videodrv.pas
  $000000010006B601  ONDRAWINDEX2,  line 2013 of chip/ps4_videodrv.pas
  $000000010006B9F0  GFX_CP_PARSER,  line 2146 of chip/ps4_videodrv.pas
  $00000001000686BC  GFX_THREAD,  line 403 of chip/ps4_videodrv.pas
  $0000000100004736
  $0000000100013A31
  $00007FF85B7A54E0
  $00007FF85CD6485B

Thanks for your hard work

**Comment by red-prig** [comment]
i will check it tomorrow

**Comment by thx4ever** [comment]
OK thanks

**Comment by red-prig** [comment]
"nop nid:*" This is a notification that the function is not implemented and will stop the emu.

**Comment by red-prig** [comment]
@thx4ever try this build https://github.com/red-prig/fpPS4/releases/tag/draft30062022

**Comment by red-prig** [comment]
![castilia](https://user-images.githubusercontent.com/68122101/176651451-14a4a708-e1f8-4768-8908-3369e8a51963.png)

**Comment by thx4ever** [comment]
Good job man. Thanks

**Comment by red-prig** [comment]
I get the same error but the game seems to work

**Comment by thx4ever** [comment]
Ahh my bad thanks too
