### ISSUE TITLE
Undertale

### ISSUE THREAD

**Issue by BigSmart69696969** [red-prig/fpPS4#16]
I found that Undertale (CUSA09415) works!

https://user-images.githubusercontent.com/108502471/176809249-97c87d9e-ac04-4dfd-95e3-2ee52114d3ff.mp4

Not really an issue but, yeah

**Comment by red-prig** [comment]
But seriously? I didn't test Undertale lol

**Comment by BigSmart69696969** [comment]
Yeah lol, it works, I only tested some of it but it runs really quickly

**Comment by red-prig** [comment]
On AMD border its broken
![undertail](https://user-images.githubusercontent.com/68122101/176832729-78340203-8f43-4bfa-8e5a-cce9f561a864.png)

**Comment by BigSmart69696969** [comment]
Weird, I don't see that on my computer.

**Comment by red-prig** [comment]
AMD Vega 8 iGPU

**Comment by BigSmart69696969** [comment]
NVIDIA GeForce RTX 3060
