### ISSUE TITLE
Flyn boots with exception stop (Flynn.Son of Crimson)

### ISSUE THREAD

**Issue by thx4ever** [red-prig/fpPS4#18]
The game Flynn.Son of Crimson bots but get caught in a stop exception 

An unhandled exception occurred at $00000001000B5977:
EAssertionFailed: TODO (vImageTiling.pas, line 422)
  $00000001000B5977  FETCHIMAGE,  line 590 of vulkan/vImageManager.pas
  $000000010006B4EF  UPDATEGPUREGSINFO,  line 1773 of chip/ps4_videodrv.pas
  $000000010006BE31  ONDRAWINDEX2,  line 2031 of chip/ps4_videodrv.pas
  $000000010006C220  GFX_CP_PARSER,  line 2164 of chip/ps4_videodrv.pas
  $0000000100068EFC  GFX_THREAD,  line 403 of chip/ps4_videodrv.pas
  $0000000100004736
  $0000000100013A31
  $00007FFFBB7754E0
  $00007FFFBCAA485B

**Comment by darkfalzx** [comment]
As Flyn is a GameMaker Studio game, getting it to work might mean getting many others to work as well. Mystik Belle, another GMS title, terminates with the same error.

**Comment by gandalfthewhite19890404** [comment]
Suggest to close, as game-related issue was created in game-compatibility repository.
