### ISSUE TITLE
White screen in some games/demos

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [red-prig/fpPS4#19]
I noticed some games that reported as partially working does dot work on my PC.
Affected titles:
Undertale
Momodora
Sonic Mania

Affected demos:
videoout_* ELFs, there are many of them and they did worked before.

Here is log, was made with Undertale.
[log.txt](https://github.com/red-prig/fpPS4/files/9034345/log.txt)
PC specs - core I5 10400, NVIDIA RTX 2060S, NVIDIA driver 516.59, Windows 10 Pro.

**Comment by gandalfthewhite19890404** [comment]
Please, note somewhere - FPPS4 needs shaders folder, from previous releases (in example).
Issue could be marked as solved, but please, mention this somewhere, I gonna close it soon.

**Comment by red-prig** [comment]
I didn't quite understand you, the shader folder is precompiled into a release. Unfortunately, nothing is clear from the log, and it breaks off, the last lines are missing.

**Comment by gandalfthewhite19890404** [comment]
Ah, see, thanks.
