### ISSUE TITLE
Change description.

### ISSUE THREAD

**Issue by jonahnm** [red-prig/fpPS4#195]
The line "PS4 compatibility layer (emulator)" could confuse people, as a compatibility layer and an emulator are very different, please change it to just say "emulator".

**Comment by red-prig** [comment]
Firstly, the very definition of “compatibility layer” creates more confusion, secondly, I think that the definition of an emulator does not contradict the concept of “compatibility layer”, and thirdly, a mixed approach is used to simulate the system.

**Comment by klaxons1** [comment]
Почитал, все равно не понял. В моем понимании слой совместимости типа как вайн, минимум оверхеда просто своя реализация винапи, а эмулятор звучит будто что-то более масштабное и сложное

**Comment by red-prig** [comment]
The compatibility layer is an implementation detail
