### ISSUE TITLE
Because PS4 uses AMD CPU, there is no need for instruction set conversion on x86 devices.

### ISSUE THREAD

**Issue by daiaji** [red-prig/fpPS4#205]
Does this mean that in reality, this is more efficient than the PS3 simulator?

**Comment by gandalfthewhite19890404** [comment]
We need to handle some AMD exclusive SSE4a instructions on Intel CPUs anyway.

**Comment by Bruniiin** [comment]
test ignore

**Comment by red-prig** [comment]
Everything that is called PS3 simulator is definitely fake, it is called an emulator, and you are asking the question incorrectly, the effectiveness of emulation of completely different systems cannot be compared
