### ISSUE TITLE
how to contribute ?

### ISSUE THREAD

**Issue by garsbien** [red-prig/fpPS4#22]
hello I realized while compiling that I have an fpPS4.lps file that you did not have. So are you interested? how to post it, please? moreover my .exe is about 40mb and works.

Thx in advance ♥

**Comment by red-prig** [comment]
*.lps are local project settings.
40mb size is normal, information for the debugger is precompiled there.

**Comment by garsbien** [comment]
thx I thought it was something else, good evening !
