### ISSUE TITLE
Buggy shaders pls fix!!! I'm very impressed but im cant using it beacuse of this !!!

### ISSUE THREAD

**Issue by sussybro** [red-prig/fpPS4#25]
![bug](https://user-images.githubusercontent.com/93008762/181507188-2767312c-d9d7-433f-8791-88b4a153a813.PNG)
I'm tired of thisssss pls fixxxxxx!!!!!!!!!!!!!!!!!!!!!

**Comment by red-prig** [comment]
Give me more information. What video card do you have? I have a few guesses about this, but I don't think I can fix it anytime soon.

**Comment by sussybro** [comment]
![ihavethis](https://user-images.githubusercontent.com/93008762/181613979-7de2eb6a-18eb-4fab-a066-78ee8fc50d05.PNG)

**Comment by sussybro** [comment]
I have this

**Comment by sussybro** [comment]
I have opening gif too im sending it

**Comment by sussybro** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/93008762/181615222-c9eb1e9b-17ba-4fd6-a76f-195b246e3cc9.gif)

**Comment by sussybro** [comment]
And pls fix it plsss.

**Comment by red-prig** [comment]
try this artifact build https://github.com/red-prig/fpPS4/suites/7393465121/artifacts/301075232 is the problem still happening?

**Comment by sussybro** [comment]
Not works :,(

**Comment by sussybro** [comment]
Here is the gif : 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/93008762/181627503-0ecbd9e2-cfc9-49ef-b0a7-f824c0d316a6.gif)

**Comment by sussybro** [comment]
:,( im sad i know c++ but its not c++.

**Comment by sussybro** [comment]
I fixed itttttttt! XD 
On this video : https://www.youtube.com/watch?v=f6YroiE5M0Y&t=2s&ab_channel=BrutalSam
It's not work on me in github build but working link in the video's description
The link is : https://www.mediafire.com/file/9jm0a1t7tuatfq4/fpPS4_30052022.zip/file
The zip file is : 
[fpPS4_30052022 (1).zip](https://github.com/red-prig/fpPS4/files/9219719/fpPS4_30052022.1.zip)
My all thanks to you red-prig!

**Comment by sussybro** [comment]
For all your hardworks!!!
Thanks!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by red-prig** [comment]
Although one of the ancient builds works, this is essentially not a fix.

**Comment by gandalfthewhite19890404** [comment]
Try to replace executable by new, from recent builds, how it works?

**Comment by sussybro** [comment]
idk if i replace its not work (fixed)

**Comment by ArbestRi** [comment]
Can this issue be closed? @red-prig has fixed the shaders in the recent fpPS4 builds.

**Comment by red-prig** [comment]
Use the setting to solve the problem: -h DISABLE_SRGB_HACK.
As long as it is.

**Comment by paulomanrique** [comment]
This setting does not work for me.

**Comment by red-prig** [comment]
@paulomanrique Perhaps you are using an old version, try downloading a new one from automatic builds https://github.com/red-prig/fpPS4/actions -> [workflow] -> Artifacts
