### ISSUE TITLE
Nothing is displaying

### ISSUE THREAD

**Issue by Piratefoxy216** [red-prig/fpPS4#31]
When I open up Sonic Mania the sounds work, though I get a blank window. The last time I used fpPS4 was in ‎September. I have a Geforce 1660 Super, 16 gigs of ram, and a intel cpu i5

Errors:
Warn, file libSceNpSnsFacebookDialog.prx not loaded!
Warn, file libSceNpSns.prx not loaded!
Warn, file libSceGameCustomDataDialog.prx not loaded!
Warn, file libSceNpAuth.prx not loaded!
Warn, file libSceInvitationDialog.prx not loaded!
Warn, file libSceNpUtility.prx not loaded!
Warn, file libSceNpTus.prx not loaded!
Warn, file libSceNpWebApi.prx not loaded!
Warn, file libSceSsl.prx not loaded!

**Comment by red-prig** [comment]
@Piratefoxy216 What emulator version are you using? What are the hack settings on the command line? Also, what files are located in the emulator folder? All of this matters.

**Comment by Piratefoxy216** [comment]
I am using the version from https://github.com/red-prig/fpPS4/actions/runs/3609800772 I am not using any hack settings in cmd.

This is what I have for the emulator 
![image](https://user-images.githubusercontent.com/62845931/205464828-0e394e16-f7cc-4d68-b3f8-fa3e4da0ae10.png)

**Comment by Boiiiiiiiiiiiiiiiiiiii** [comment]
> I am using the version from https://github.com/red-prig/fpPS4/actions/runs/3609800772 I am not using any hack settings in cmd.
> 
> This is what I have for the emulator. And a folder named "shader_dump" ![image](https://user-images.githubusercontent.com/62845931/205464828-0e394e16-f7cc-4d68-b3f8-fa3e4da0ae10.png)

Try using hacks

**Comment by Piratefoxy216** [comment]
> > I am using the version from https://github.com/red-prig/fpPS4/actions/runs/3609800772 I am not using any hack settings in cmd.
> > This is what I have for the emulator. And a folder named "shader_dump" ![image](https://user-images.githubusercontent.com/62845931/205464828-0e394e16-f7cc-4d68-b3f8-fa3e4da0ae10.png)
> 
> Try using hacks. Mainly, -h IMAGE_TEST_HACK & -h IMAGE_LOAD_HACK

That sucks, it didn't work

**Comment by Piratefoxy216** [comment]
"fpPS4.exe -e "D:\ps4 emulator\game\eboot.bin" -h IMAGE_TEST_HACK & -h IMAGE_LOAD_HACK"

![image](https://user-images.githubusercontent.com/62845931/205510686-7e7725b2-7eb2-40e2-b2ed-ff2644baed7d.png)

**Comment by red-prig** [comment]
@Piratefoxy216 try:
`fpPS4.exe -e "D:\ps4 emulator\game\eboot.bin" -h IMAGE_TEST_HACK`

**Comment by Piratefoxy216** [comment]
It still isn't working unfortunately

**Comment by red-prig** [comment]
@Piratefoxy216 I have no more ideas what is wrong.

**Comment by red-prig** [comment]
@Piratefoxy216 You can go to the discord https://discord.gg/7JnYvKnJxM maybe someone will help you, there you can drop the log file

**Comment by Piratefoxy216** [comment]
I just got the latest version again from the actions, it works now

**Comment by thechairman031** [comment]
> I just got the latest version again from the actions, it works now

ı got the same problem. what it is you got the lastest version of  ?

**Comment by shadooww** [comment]
https://pastebin.com/rbWj4PMY

**Comment by red-prig** [comment]
@Shadwbtw Why are people trying to launch games that no one has announced support for?

**Comment by shadooww** [comment]
> @Shadwbtw Why are people trying to launch games that no one has announced support for?

So i cant play ufc 4?
