### ISSUE TITLE
Loading From Script -  White Screen and Forcing Full Screen

### ISSUE THREAD

**Issue by GeorgeSpiggott** [red-prig/fpPS4#35]
Not strictly an issue, just some quirky features and a workaround for one of them.

If you open fpPS4 from a script fpPS4 will create a shader_dump folder in the same folder as the scrip was launched from. The result will be the game opens with a white screen. Changing the directory in the script to the fpPS4 application folder solves this. 

It is possible to force the 'terminal' window into a full screen window but is it possible to do the same with the 'emulation' window when launching from a script?

**Comment by red-prig** [comment]
This is rather strange, but on the latest versions of such problems should not be.

**Comment by red-prig** [comment]
While there is one possibility to go to full screen by pressing Alt-Enter in the game window.

**Comment by GeorgeSpiggott** [comment]
Thanks. Maybe I can tie that to a button config in JoytoKey.

**Comment by GeorgeSpiggott** [comment]
> 

I'm using this version here: https://github.com/red-prig/fpPS4/actions/runs/3609800772 Is this the best way to get the latest version?

**Comment by GeorgeSpiggott** [comment]
I've just started to use the new version. Some great improvements. Is full-screen (Alt and Enter) accessible through the command line?

**Comment by red-prig** [comment]
> I've just started to use the new version. Some great improvements. Is full-screen (Alt and Enter) accessible through the command line?

not

**Comment by GeorgeSpiggott** [comment]
I've been using the Launcher for a while and have just come back to using scripts. I've just noticed that some games (Dead Cells and We are Doomed) still need the directory changing when launched from a script or else the cannot find library files. They work fine through the Launcher without modification. 

[Edit] Temporary fix for this, copied the "sce_module" folder to the location of the script.
