### ISSUE TITLE
New Version of my GUI (old was wrong)

### ISSUE THREAD

**Issue by SlrHui** [red-prig/fpPS4#37]
Hello, enclosed you can find a new version of my GUI.
The previous one was unfortunately an ancient wrong version.
This one is programmed in C# with Net Core 6.
I have updated the GUI. Now you can start game/app by double click.
Most parameters are supported. 
You can add pict.jpg at the location of game/app to display it properly on list.
e.g. apps/apptest/pict.jpg apps/apptest1/pict.jpg
the cmd window can be redirected to the gui and with the button "copy to clipboard" the content can be copied to the clipboard.
Sorry for my english. I used a translator.

This version still comes without source code. 
Greetings SLRHUI
![screenshot](https://user-images.githubusercontent.com/108663189/208064899-512b2717-583b-45d6-98e8-57a543225ecd.jpg)

[fpps4fro.zip](https://github.com/red-prig/fpPS4/files/10244307/fpps4fro.zip)

**Comment by red-prig** [comment]
To be honest, I do not know how to react to the fact that the source code of the project is closed.

**Comment by SlrHui** [comment]
hello, next time I'll send it along again.
i just need to add comments to make it easier to read. and right now i'm a little short on time because christmas is just around the corner.

**Comment by SlrHui** [comment]
ok here is the sourcecode without comments.
[source.zip](https://github.com/red-prig/fpPS4/files/10265935/source.zip)
