### ISSUE TITLE
Missing spirv folder?

### ISSUE THREAD

**Issue by mrsteyk** [red-prig/fpPS4#4]
I know this is a meme and all but it doesn't appear to have `spirv` folder with VS and PS shaders because it's in gitignore...

**Comment by red-prig** [comment]
i know i will public this later, there is a very crude recompiler in there which i don't want to show yet

**Comment by red-prig** [comment]
shader recompiler added to trunk branch

**Comment by red-prig** [comment]
shader recompiler added to trunk branch
