### ISSUE TITLE
prx files

### ISSUE THREAD

**Issue by Squidtito** [red-prig/fpPS4#45]
Hi, I was wondering where I would find prx files like libSceNgs, I have my ps4 looking through the files with FTP

**Comment by red-prig** [comment]
idk

**Comment by Squidtito** [comment]
xd

**Comment by mailwl** [comment]
it's useless, because of encryption. You have to use something like OrbisMAN homebrew, to decrypt file system

**Comment by red-prig** [comment]
@mailwl The FTP server currently decrypts files on the fly, so no need to

**Comment by gandalfthewhite19890404** [comment]
Close, please
