### ISSUE TITLE
Latest fpps4 build broke all Microsoft Mono games

### ISSUE THREAD

**Issue by ghost** [red-prig/fpPS4#49]
Every single Microsoft Mono game wouldn't show graphical output or ANYTHING! I tested all of them with red-prig/fpPS4@aaa34d3.

**Comment by gandalfthewhite19890404** [comment]
Here is Feist, mono was used.
![image](https://user-images.githubusercontent.com/24764335/210300982-1cc25ba9-2e7b-411c-90fb-786c1c9dde40.png)

**Comment by red-prig** [comment]
@ArbestRi Name a specific game with regression, your statements are too general.

**Comment by ghost** [comment]
@red-prig Here are the games I tried but wouldn't load:
Laser Disco Defenders (uses Mono)
Lovers in a Dangerous Spacetime
Also broke some games running different engines:
Toby and the Secret Mine (likely uses Unity)
Umihara Kawase BaZooKa! (game shows a output window but won't show any visual)
Moving Out (uses Unity)
I also have libraries for Mono in my sce-module folder.

**Comment by red-prig** [comment]
@ArbestRi 
![toby](https://user-images.githubusercontent.com/68122101/210315734-bcbd7144-582d-4498-b9ba-09d7593833e2.png)
it worked normaly

**Comment by red-prig** [comment]
![ukb](https://user-images.githubusercontent.com/68122101/210317712-caef6fcb-cebd-46e9-ab3d-b4541359653a.png)
If you poke x in a non-drawing menu, then it comes to the gameplay

**Comment by ghost** [comment]
@red-prig How do I do that?

**Comment by red-prig** [comment]
@ArbestRi Have you used the hacks described here?: https://github.com/red-prig/fpps4-game-compatibility/issues/623

**Comment by ghost** [comment]
I tried the hacks with all the broken games - still nothing.

**Comment by red-prig** [comment]
Try to install the Vulkan SDK and send the game launch log after that, maybe there are some errors on the driver side, I have no more ideas.

**Comment by ghost** [comment]
I don't understand why everyone else's fpPS4 runs Mono games, but mines doesn't. I didn't install Vulkan SDK yet

**Comment by ghost** [comment]
And on my other PC, these games work
