### ISSUE TITLE
[Feature Request] Debugging Improvements

### ISSUE THREAD

**Issue by wheelmac92** [red-prig/fpPS4#5]
If an eboot contains debug symbols, can there be a feature to make them visible when debugging fpPS4 from Visual Studio? Also, when printf is called from an eboot, can this print to the output window of fpPS4? 

Would it also be possible to pause the emulator right before the eboot entry is called? Without that feature, I've been putting an infinite loop at the start of my main() just so that I can pause the debugger, then place my breakpoints, then exit the loop to start the program. It would be more convenient if the emulator had a feature to pause itself.

The existing debugging tools, such as printing assert exceptions, and the ability to set breakpoints when debugging from Visual Studio, are amazing. Love it! Looking forward to more

**Comment by red-prig** [comment]
1) Visual Studio? did you mean Lazarus IDE? 
2) some programs contain dwarf sections, but I cannot imagine how it is painless to transfer this to ide or debugger, without ide patching
3) yes, printf inside eboot worked
4) use in debug inside lazarus ide runing, pause and set breakpoints works, no another way
5) assert inside eboot also worked

**Comment by wheelmac92** [comment]
I was not using Lazarus IDE, I was using Visual Studio, I dragged the fpPS4 emulator exe into visual studio (dont need the emu source code), then hit Start Debugging. Is Lazarus better?

**Comment by red-prig** [comment]
oh you mean asm debug without source? i use ghidra from disassemble and all
