### ISSUE TITLE
Sonic Mania Not Launching

### ISSUE THREAD

**Issue by giver09** [red-prig/fpPS4#53]
I tried pressing the run fpPS4 button after setup, but all I get is this message:

INFO - Running fpPS4 with args: -e C:/Users/pilot/fpPS4/Games/Sonic Mania/eboot.bin
Emu location: C:/Users/pilot/fpPS4/Emu/fpPS4.exe

INFO - (CUSA07010) Skip updating settings file since it had no changes!
 
INFO - fpPS4.exe was closed returning code 3221225781

**Comment by red-prig** [comment]
Apparently you are missing some system libraries in your operating system, or the operating system does not meet the minimum system requirements, or your antivirus is blocking the launch, try running fpps4.exe directly and provide an error message if it appears.

**Comment by GeorgeSpiggott** [comment]
Sonic Mania doesn't actually need any additional libraries to run so it may be something else.

**Comment by red-prig** [comment]
Error 3221225781 means that some library of the Windows operating system was not found, do not confuse it with prx in this case.

**Comment by GeorgeSpiggott** [comment]
Thanks for the clarification.

**Comment by flyingtincan** [comment]
Could be missing XInput1_3.dll. Try installing https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by giver09** [comment]
Downloading DirectX made it work flawlessly, thank you.
