### ISSUE TITLE
Result.Bits[i]:=src.Bits[count-i];  Illegal Quantifier

### ISSUE THREAD

**Issue by TylerJaacks** [red-prig/fpPS4#54]
I'm trying to compile fpPS4 but I get an error on line 829 of emit_post_op.pas for this function

```
Function ReverseBits(src:QWORD;count:Byte):QWORD;
var
 i:Byte;
begin
 Result:=0;
 Assert(count<>0);
 dec(count);
 For i:=0 to count do
 begin
  Result.Bits[i]:=src.Bits[count-i];
 end;
end;  
```

With the error being for the .Bits[...] field being an Illegal Quantifier. I never used FreePascal before so im not sure what is going on here.

**Comment by red-prig** [comment]
use fpc 3.3.1 (trunk), Install it via fpcupdeluxe

**Comment by TylerJaacks** [comment]
![Screenshot 2023-01-09 194529](https://user-images.githubusercontent.com/1505374/211443045-e1113315-fa71-47bb-ac83-bf6034b1ed6d.png)

I'm not sure what to do I selected trunk and this what i get.
