### ISSUE TITLE
What about a milestone game(s) for this emulator?

### ISSUE THREAD

**Issue by bpavuk** [red-prig/fpPS4#57]
I mean a list of games/programs that will be target for this emulator, I heard Wine was developed using this approach. For example, Orbis OS (aka UI of PS4) uses, for example, syscalls num1, num2 and num3, so we need to implement those syscalls first. Another example - Spider-Man, this game uses 120 different syscalls, so, if Spider-Man game is milestone, we need to implement those ones first. Such development approach will help newbies start their work fast

**Comment by ghost** [comment]
@red-prig would like that! 😁

**Comment by bpavuk** [comment]
Of course, have you ever seen developer who likes anarchy in development?

**Comment by red-prig** [comment]
I don't set the milestone game as a goal for myself yet. In the future, I will probably prioritize bloodborne, but for now, I'm describing general things.

**Comment by bpavuk** [comment]
As you wish, I just gave you advice. If I'd have any skills in С/С++ and reverse engineering I would commit using this strategy and old versions of Minecraft game as an easy start
