### ISSUE TITLE
Memory Issue.

### ISSUE THREAD

**Issue by BenHilling** [red-prig/fpPS4#9]
I get the memory issue vkAllocateMemory:VK_ERROR_OUT_OF_DEVICE_MEMORY halfway through loading a game

**Comment by red-prig** [comment]
@BenHilling What game is this? What video card do you have? In fact, this message means that there is not enough video memory for the game.

**Comment by BenHilling** [comment]
I have a 1660 super and Im trying to play persona 5 royal

**Comment by BenHilling** [comment]
which is 6GB of vram

**Comment by red-prig** [comment]
@BenHilling  Persona 5 is not yet supported by this emulator, you're in the wrong place))

**Comment by BenHilling** [comment]
Oh.
