### ISSUE TITLE
TODO vImage (many games)

### ISSUE THREAD

**Issue by ghost** [red-prig/fpPS4#91]
This is starting to appear way too often. It would be nice if this TODO in vImage was fixed 🙂
All affected games:
Descenders
Sonic Colors Ultimate
Demons Crystals
Farm Together
Bendy and the Ink Machine
and some more.

**Comment by gandalfthewhite19890404** [comment]
Why we need that issue, we can filter labels in tracker

**Comment by ghost** [comment]
@gandalfthewhite19890404 Closed this issue because of that

**Comment by ghost** [comment]
Might still be good

**Comment by ghost** [comment]
The TODO in vImage is now fixed
