### ISSUE TITLE
fpPS4 does not work at all

### ISSUE THREAD

**Issue by ghost** [red-prig/fpPS4#96]
No matter how hard I try, I can't get fpPS4 to run on my PC.
![image](https://user-images.githubusercontent.com/86171223/223599640-3244cac3-ca04-4f63-844f-88af4a9acd4e.png)
I also have the DLLs needed.
![image](https://user-images.githubusercontent.com/86171223/223599707-faedac0b-9e8d-4c44-a688-7adfde668d16.png)

**Comment by ghost** [comment]
It might be because I'm missing `xinput.dll`.
I ran fpPS4 as admin and it said I'm missing a DLL.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/86171223/223599976-c1b77ebd-93a3-482f-8c68-28aead648ca4.png)

**Comment by ghost** [comment]
Tried installing it, but got a different error:
![image](https://user-images.githubusercontent.com/86171223/223600456-1fa1f857-bb42-4638-b985-627a2e33c31b.png)

**Comment by ghost** [comment]
I have problem too

**Comment by ghost** [comment]
it's help for this problem?

**Comment by HugoMoranunico** [comment]
I have the same problem, need help
